import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Main from './components/Main'
import React, { useState, useEffect } from 'react'
import Login from './Login'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>TML</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main}`}>
          {/* <Main data = {props} render = {{render, setRender}} /> */}
          <Login />
      </main>

    </div>
  )
}
