import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.min.css'
import 'react-toastify/dist/ReactToastify.css';
import Main from './Main'
import React, { useState, useEffect } from 'react'
import { useRouter } from 'next/router';

export default function Home(props) {

  return (
    <div className={styles.container}>
      <Head>
        <title>TML</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <Main data = {props}/>
      </main>

      <footer className={`${styles.footer}`}>
        <a
          href="#"
          target="_blank"
          rel="noopener noreferrer"
          className='font-bold'
        >
          TML{' '}
          <span className={`${styles.logo} `}>
          
          </span> 
        </a>
      </footer>
    </div>
  )
}

export const getStaticProps = async (context) => {

  const res = await fetch('http://122.201.28.39:8081/api/db')
  const db = await res.json()

  const res1 = await fetch('http://122.201.28.39:8081/api/trade')
  const trade = await res1.json()

  return {
      props: {
        db: db,
        trade: trade
      },
      revalidate: 30,
  }
}
