import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Main from './components/Main'
import React, { useState, useEffect } from 'react'
import { useRouter } from 'next/router'

export default function Home(props) {
  const [render, setRender] = useState(false);
  const router = useRouter()
  function login() {
    router.push({
      pathname: '/components/Main'
    })
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>TML</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main}`}>
          <div className='border p-2 bg-gray-500 cursor-pointer w-1/3 text-white rounded-xl text-center mx-auto my-auto' onClick={login}>
            Login
          </div>
      </main>

    </div>
  )
}
